SENSORS_LINEAR = "Linear"
SENSORS_ANGULAR = "Angular"
SENSORS_DATA = "Data"
MOTOR_HEALTH = "Health"
TARGET_LOCATION = "Target Location"
MASTER_CONTROL = "Control"
MASTER_GOALS = "Goals"

MASTER_SERVER_ID = 42
SENSOR_SERVER_ID = 43
MOTOR_SERVER_ID = 44
FORWARD_VISION_SERVER_ID = 45
DOWNWARD_VISION_SERVER_ID = 46
SONAR_SERVER_ID = 47

MASTER_SERVER_IP = "10.0.0.42"
SENSOR_SERVER_IP = "10.0.0.43"
MOTOR_SERVER_IP = "10.0.0.44"
FORWARD_VISION_SERVER_IP = "10.0.0.45"
DOWNWARD_VISION_SERVER_IP = "10.0.0.46"
SONAR_SERVER_IP = "10.0.0.47"
