SENSORS_LINEAR = "linear"
SENSORS_ANGULAR = "angular"
SENSORS_DATA = "data"
MOTOR_HEALTH = "health"
MOTOR_KILL = "kill"
TARGET_LOCATION = "targetlocation"
TARGET_LOCATION_AND_ROTATION = "targetLocAndRot"
MASTER_CONTROL = "control"
MASTER_GOALS = "goals"
MASTER_SENSOR_RESET = "sensorreset"

MASTER_SERVER_ID = 42
SENSOR_SERVER_ID = 43
MOTOR_SERVER_ID = 44
FORWARD_VISION_SERVER_ID = 45
DOWNWARD_VISION_SERVER_ID = 46
SONAR_SERVER_ID = 47

MASTER_SERVER_IP = "10.0.0.42"
SENSOR_SERVER_IP = "10.0.0.43"
MOTOR_SERVER_IP = "10.0.0.44"
FORWARD_VISION_SERVER_IP = "10.0.0.45"
DOWNWARD_VISION_SERVER_IP = "10.0.0.46"
SONAR_SERVER_IP = "10.0.0.47"
